import type { PlayerStatus, PositionCode } from "./auctionData";

export type ExpandedPlayerSeed = [name: string, position: PositionCode, rating: number, status: PlayerStatus];

const seed = (position: PositionCode, names: Array<[string, number, PlayerStatus?]>) => names.map(([name, rating, status = "active"]) => [name, position, rating, status] as ExpandedPlayerSeed);

export const expandedPlayerSeeds: ExpandedPlayerSeed[] = [
  ...seed("GK", [
    ["José Luis Chilavert", 87, "legend"], ["Peter Schmeichel", 91, "legend"], ["Oliver Kahn", 91, "legend"], ["Sepp Maier", 89, "legend"], ["Walter Zenga", 87, "legend"], ["Claudio Taffarel", 87, "legend"], ["Jorge Campos", 84, "legend"], ["Rinat Dasayev", 88, "legend"], ["Gordon Banks", 91, "legend"], ["Ray Clemence", 88, "legend"], ["Bruce Grobbelaar", 85, "legend"], ["David Seaman", 88, "legend"], ["Edwin van der Sar", 90, "legend"], ["Fabien Barthez", 86, "legend"], ["Victor Valdés", 86, "legend"], ["Wojciech Szczęsny", 85], ["Mike Maignan", 87], ["Emiliano Martínez", 87], ["Édouard Mendy", 83], ["André Onana", 84], ["Yassine Bounou", 85], ["Keylor Navas", 87], ["Hugo Lloris", 87, "legend"], ["Sami Hyypiä", 82, "legend"], ["Kasper Schmeichel", 83], ["Jordan Pickford", 84], ["Nick Pope", 83], ["Unai Simón", 83], ["David de Gea", 87], ["Kepa Arrizabalaga", 81], ["Bernd Leno", 82], ["Rui Patrício", 84], ["Anthony Lopes", 82], ["Łukasz Fabiański", 80], ["Sergio Romero", 82, "legend"], ["Claudio Bravo", 85, "legend"], ["Fernando Muslera", 84], ["Rafael Márquez", 80, "legend"], ["Essam El Hadary", 82, "legend"], ["Ahmed El Shenawy", 78], ["Mohamed El Shenawy", 82], ["Gianluca Pagliuca", 88, "legend"], ["Angelo Peruzzi", 87, "legend"], ["Nery Pumpido", 84, "legend"], ["Dida", 88, "legend"]
  ]),
  ...seed("CB", [
    ["Bobby Moore", 93, "legend"], ["Franco Baresi", 94, "legend"], ["Gaetano Scirea", 93, "legend"], ["Daniel Passarella", 91, "legend"], ["Marcel Desailly", 91, "legend"], ["Lilian Thuram", 90, "legend"], ["Laurent Blanc", 90, "legend"], ["Jaap Stam", 89, "legend"], ["Nemanja Vidić", 90, "legend"], ["John Terry", 91, "legend"], ["Sol Campbell", 87, "legend"], ["Gary Pallister", 85, "legend"], ["Martin Keown", 84, "legend"], ["Jürgen Kohler", 88, "legend"], ["Matthias Sammer", 89, "legend"], ["Mats Hummels", 87], ["Gerard Piqué", 89, "legend"], ["Javier Mascherano", 87, "legend"], ["Diego Godín", 88, "legend"], ["Giorgio Chiellini", 90, "legend"], ["Leonardo Bonucci", 88, "legend"], ["Andrea Barzagli", 87, "legend"], ["Gianluca Mancini", 82], ["Stefan de Vrij", 85], ["Matthijs de Ligt", 86], ["Éder Militão", 86], ["Antonio Rüdiger", 87], ["David Alaba", 88], ["Raphaël Varane", 89, "legend"], ["Presnel Kimpembe", 82], ["Marquinhos", 88], ["Thiago Djalo", 79], ["Lisandro Martínez", 85], ["Cristian Romero", 86], ["Nicolás Otamendi", 86, "legend"], ["Walter Samuel", 89, "legend"], ["Gabriel Heinze", 84, "legend"], ["Iván Córdoba", 87, "legend"], ["José María Giménez", 84], ["Nayef Aguerd", 82], ["Wesley Fofana", 82], ["Jonathan Tah", 84], ["Niklas Süle", 84], ["Matthias Ginter", 82], ["Ahmed Hegazi", 80], ["Ramy Rabia", 78], ["Ali Gabr", 77], ["Mahmoud Hamdy El Wensh", 76], ["Ayman Ashraf", 76]
  ]),
  ...seed("RB", [
    ["Carlos Alberto", 93, "legend"], ["Djalma Santos", 91, "legend"], ["Berti Vogts", 88, "legend"], ["Mauro Tassotti", 87, "legend"], ["Míchel Salgado", 87, "legend"], ["Gary Neville", 87, "legend"], ["Wes Brown", 81, "legend"], ["Steve Finnan", 82, "legend"], ["Glen Johnson", 82, "legend"], ["Bacary Sagna", 84, "legend"], ["Ivanović", 85, "legend"], ["Branislav Ivanović", 85, "legend"], ["César Azpilicueta", 86], ["Héctor Bellerín", 81], ["Aaron Wan-Bissaka", 82], ["Ben White", 85], ["Kieran Trippier", 85], ["Tino Livramento", 79], ["Diogo Dalot", 82], ["Noussair Mazraoui", 83], ["Benjamin Pavard", 84], ["Jonathan Clauss", 82], ["Sergiño Dest", 79], ["Timothy Castagne", 80], ["Vanderson", 80], ["Emerson Royal", 80], ["Malo Gusto", 81], ["Martín Montoya", 79, "legend"], ["Hugo Mallo", 80, "legend"], ["Antonio Valencia", 88, "legend"], ["Maicon", 92, "legend"], ["Douglas Maicon", 92, "legend"], ["Danilo", 84], ["Marcos Cafú", 91, "legend"], ["Nelson Semedo", 81], ["Sime Vrsaljko", 82, "legend"], ["Daryl Janmaat", 79, "legend"], ["Mário Fernandes", 81, "legend"], ["Abdulrahman Al-Obaid", 75], ["Mohamed Hany", 78], ["Omar Kamal", 76], ["Ahmed Fathi", 81, "legend"], ["Hossam Ashour", 80, "legend"], ["Sergi Roberto", 82], ["Sacha Boey", 80], ["Iván Fresneda", 78]
  ]),
  ...seed("LB", [
    ["Nilton Santos", 92, "legend"], ["Giacinto Facchetti", 92, "legend"], ["Paul Breitner", 89, "legend"], ["Karl-Heinz Schnellinger", 87, "legend"], ["Bixente Lizarazu", 89, "legend"], ["Patrice Evra", 88, "legend"], ["Gaël Clichy", 82, "legend"], ["Kieran Gibbs", 79, "legend"], ["Wayne Bridge", 82, "legend"], ["Eric Abidal", 87, "legend"], ["Maxwell", 87, "legend"], ["Filipe Luís", 87, "legend"], ["Alex Sandro", 85], ["Raphaël Guerreiro", 84], ["Luke Shaw", 83], ["Ben Chilwell", 82], ["Oleksandr Zinchenko", 84], ["Kieran Tierney", 82], ["Andy Robertson", 87], ["Kostas Tsimikas", 80], ["Sergio Reguilón", 80], ["José Gayà", 84], ["Marcos Acuña", 84], ["Nicolás Tagliafico", 83], ["Pervis Estupiñán", 82], ["Milos Kerkez", 79], ["Rayan Aït-Nouri", 80], ["Ian Maatsen", 80], ["Patrick van Aanholt", 80, "legend"], ["Daley Blind", 84, "legend"], ["Jan Vertonghen", 86, "legend"], ["César Azpilicueta", 86], ["Fábio Coentrão", 86, "legend"], ["José Enrique", 82, "legend"], ["Adriano", 84, "legend"], ["Juan Pablo Sorín", 88, "legend"], ["Gabriel Heinze", 84, "legend"], ["Jesús Navas", 84, "legend"], ["Abner Vinícius", 77], ["Yuto Nagatomo", 82, "legend"], ["Hiroki Ito", 80], ["Ahmed Abu El Fotouh", 78], ["Ali Maaloul", 83, "legend"], ["Amr El Solia", 80, "legend"], ["Karim Hafez", 77], ["Mohamed Hamdy", 76]
  ]),
  ...seed("CM", [
    ["Didi", 92, "legend"], ["Bobby Charlton", 93, "legend"], ["Günter Netzer", 90, "legend"], ["Lothar Matthäus", 93, "legend"], ["Frank Rijkaard", 91, "legend"], ["Clarence Seedorf", 91, "legend"], ["Michael Ballack", 89, "legend"], ["Steven Gerrard", 91, "legend"], ["Frank Lampard", 91, "legend"], ["Roy Keane", 90, "legend"], ["Michael Carrick", 86, "legend"], ["Darren Fletcher", 82, "legend"], ["Cesc Fàbregas", 89, "legend"], ["David Silva", 91, "legend"], ["Santi Cazorla", 87, "legend"], ["Sergio Busquets", 91, "legend"], ["Xabi Alonso", 90, "legend"], ["Marcos Senna", 85, "legend"], ["Mikel Arteta", 84, "legend"], ["Thiago Alcântara", 88], ["Marco Verratti", 87], ["Jorginho", 86], ["Nicolò Barella", 87], ["Hakan Çalhanoğlu", 86], ["Adrien Rabiot", 83], ["Eduardo Camavinga", 85], ["Aurélien Tchouaméni", 86], ["Enzo Fernández", 85], ["Alexis Mac Allister", 86], ["Moisés Caicedo", 83], ["Bruno Guimarães", 84], ["Casemiro", 89, "legend"], ["Fabinho", 87, "legend"], ["Fernandinho", 88, "legend"], ["Paulinho", 83, "legend"], ["Ramires", 85, "legend"], ["Gilberto Silva", 87, "legend"], ["Dunga", 89, "legend"], ["Socrates", 93, "legend"], ["Falcão", 92, "legend"], ["Claudio Marchisio", 87, "legend"], ["Radja Nainggolan", 85, "legend"], ["Marek Hamšík", 86, "legend"], ["Nabil Bentaleb", 79], ["Bastian Schweinsteiger", 89, "legend"], ["Sami Khedira", 86, "legend"], ["Mohamed Elneny", 79], ["Tarek Hamed", 80, "legend"], ["Hamdy Fathy", 79], ["Mohamed Aboutrika", 88, "legend"]
  ]),
  ...seed("CAM", [
    ["Michel Platini", 95, "legend"], ["Johan Cruyff", 96, "legend"], ["Eusébio", 94, "legend"], ["George Best", 94, "legend"], ["Roberto Baggio", 93, "legend"], ["Rivaldo", 93, "legend"], ["Manuel Rui Costa", 89, "legend"], ["Dejan Stanković", 87, "legend"], ["Pavel Nedvěd", 91, "legend"], ["Michael Laudrup", 93, "legend"], ["Dennis Bergkamp", 92, "legend"], ["Eric Cantona", 91, "legend"], ["Wayne Rooney", 91, "legend"], ["Juan Mata", 86, "legend"], ["Mason Mount", 82], ["Kai Havertz", 84], ["Thomas Müller", 89, "legend"], ["Mario Götze", 84, "legend"], ["Christian Eriksen", 87], ["James Maddison", 84], ["Mikel Oyarzabal", 83], ["Isco", 87, "legend"], ["Marco Reus", 86, "legend"], ["Dimitri Payet", 85, "legend"], ["Henrikh Mkhitaryan", 84, "legend"], ["Hakim Ziyech", 83], ["Sofiane Boufal", 80], ["Yacine Brahimi", 82, "legend"], ["Samir Nasri", 84, "legend"], ["Rui Costa", 89, "legend"], ["Alex de Souza", 87, "legend"], ["Juan Sebastián Verón", 89, "legend"], ["Pablo Aimar", 88, "legend"], ["Ariel Ortega", 87, "legend"], ["Ángel Di María", 90, "legend"], ["Javier Pastore", 82, "legend"], ["Rafinha Alcântara", 83], ["Giovani Lo Celso", 82], ["Dominik Szoboszlai", 84], ["Maddison", 84], ["Mostafa Mohamed", 78], ["Abdallah El Said", 82, "legend"], ["Shikabala", 81, "legend"], ["Walid Soliman", 80, "legend"], ["Amr Warda", 76]
  ]),
  ...seed("RW", [
    ["Stanley Matthews", 93, "legend"], ["Jairzinho", 94, "legend"], ["Tom Finney", 90, "legend"], ["Omar Sívori", 91, "legend"], ["Hristo Stoichkov", 92, "legend"], ["Rene van de Kerkhof", 87, "legend"], ["Joaquín Sánchez", 84, "legend"], ["Pedro Rodríguez", 87, "legend"], ["Jesús Navas", 85, "legend"], ["Willian", 84, "legend"], ["Lucas Moura", 82, "legend"], ["Antony", 80], ["Raphinha", 85], ["Rodrygo", 86], ["Raphinha", 85], ["Rafael Leão", 88], ["Federico Chiesa", 86], ["Nico González", 82], ["Ferran Torres", 82], ["Adama Traoré", 82], ["Samuel Chukwueze", 81], ["Yeremy Pino", 81], ["Takefusa Kubo", 84], ["Moussa Diaby", 84], ["Kingsley Coman", 86], ["Serge Gnabry", 87], ["Leroy Sané", 87], ["Thomas Lemar", 82], ["Domenico Berardi", 84], ["Ricardo Quaresma", 85, "legend"], ["Nani", 87, "legend"], ["Jérémy Ménez", 82, "legend"], ["Marek Heinz", 78, "legend"], ["Andriy Yarmolenko", 82, "legend"], ["Willian Borges", 84, "legend"], ["Hatem Ben Arfa", 84, "legend"], ["Adel Taarabt", 82, "legend"], ["Ahmed Hassan", 84, "legend"], ["Trézéguet", 82], ["Mostafa Mohamed", 78], ["Mahmoud Kahraba", 80, "legend"], ["Hussein El Shahat", 81], ["Emam Ashour", 80], ["Omar Marmoush", 84], ["Ibrahim Adel", 76]
  ]),
  ...seed("LW", [
    ["Pelé", 98, "legend"], ["Gordon Banks", 80, "legend"], ["George Weah", 94, "legend"], ["Romário", 94, "legend"], ["Kenny Dalglish", 92, "legend"], ["Kevin Keegan", 91, "legend"], ["Dragan Džajić", 90, "legend"], ["Rivaldo", 93, "legend"], ["Rivaldo", 93, "legend"], ["Roberto Mancini", 87, "legend"], ["David Ginola", 87, "legend"], ["Marc Overmars", 89, "legend"], ["Ryan Giggs", 92, "legend"], ["Park Ji-sung", 84, "legend"], ["Arda Turan", 84, "legend"], ["Willian José", 80], ["Anthony Martial", 82], ["Marcus Rashford", 85], ["Jadon Sancho", 84], ["Jack Grealish", 85], ["Gabriel Martinelli", 84], ["Gabriel Jesus", 85], ["Raphinha", 85], ["Rodrygo", 86], ["Rafael Leão", 88], ["Nuno Santos", 80], ["Nani", 87, "legend"], ["Ludovic Giuly", 83, "legend"], ["Florent Malouda", 86, "legend"], ["Sylvain Wiltord", 84, "legend"], ["Sidney Govou", 80, "legend"], ["Miroslav Klose", 90, "legend"], ["Claudio Caniggia", 89, "legend"], ["Oleg Salenko", 82, "legend"], ["Hernán Crespo", 90, "legend"], ["Javier Saviola", 85, "legend"], ["Carlos Tevez", 90, "legend"], ["Ángel Correa", 83], ["Giovanni Simeone", 81], ["Nicolás González", 82], ["Luis Sinisterra", 80], ["Steven Bergwijn", 82], ["Anwar El Ghazi", 79], ["Ahmed Refaat", 78, "legend"], ["Mostafa Fathi", 77, "legend"]
  ]),
  ...seed("ST", [
    ["Gerd Müller", 96, "legend"], ["Ferenc Puskás", 97, "legend"], ["Just Fontaine", 93, "legend"], ["Gabriel Batistuta", 94, "legend"], ["Alan Shearer", 93, "legend"], ["Ruud van Nistelrooy", 92, "legend"], ["Filippo Inzaghi", 88, "legend"], ["Christian Vieri", 90, "legend"], ["Hernán Crespo", 90, "legend"], ["Fernando Torres", 89, "legend"], ["David Villa", 91, "legend"], ["Raúl", 92, "legend"], ["Fernando Morientes", 88, "legend"], ["Michael Owen", 89, "legend"], ["Emile Heskey", 82, "legend"], ["Jermain Defoe", 86, "legend"], ["Peter Crouch", 82, "legend"], ["Mario Mandžukić", 88, "legend"], ["Edinson Cavani", 91, "legend"], ["Gonzalo Higuaín", 90, "legend"], ["Mauro Icardi", 84], ["Romelu Lukaku", 88], ["Álvaro Morata", 86], ["Dusan Vlahović", 84], ["Victor Boniface", 82], ["Rasmus Højlund", 82], ["Darwin Núñez", 85], ["Alexander Isak", 86], ["Jonathan David", 84], ["Ollie Watkins", 84], ["Ivan Toney", 83], ["Dominic Calvert-Lewin", 80], ["Tammy Abraham", 81], ["Patson Daka", 80], ["Ciro Immobile", 88], ["Andrea Belotti", 83], ["Domenico Berardi", 84], ["Mehdi Taremi", 84], ["Sardar Azmoun", 82], ["Taremi", 84], ["Koulibaly", 80], ["Ahmed Hassan Kouka", 78], ["Hossam Hassan", 86, "legend"], ["Mido", 82, "legend"], ["Amr Zaki", 81, "legend"]
  ])
];
