// Generated from Wikipedia page-image thumbnails. Keep URLs immutable per catalogue name.
export const PLAYER_IMAGE_URLS: Record<string, string> = {
  "Lev Yashin": "/manus-storage/lev-yashin_eb96a077.jpg",
  "Gianluigi Buffon": "/manus-storage/gianluigi-buffon_8323ca21.jpg",
  "Iker Casillas": "/manus-storage/iker-casillas_a8ff2c7c.jpg",
  "Thibaut Courtois": "/manus-storage/thibaut-courtois_9082cb9d.jpg",
  "Manuel Neuer": "/manus-storage/manuel-neuer_cb436d24.jpg",
  "Petr Čech": "/manus-storage/petr-ech_35706b83.jpg",
  "Alisson Becker": "/manus-storage/alisson-becker_d3584350.jpg",
  "Gianluigi Donnarumma": "/manus-storage/gianluigi-donnarumma_7ff5cebe.jpg",
  "Jan Oblak": "/manus-storage/jan-oblak_0d8dc935.jpg",
  "Marc-André ter Stegen": "/manus-storage/marc-andr-ter-stegen_7bd33674.jpg",
  "David Raya": "/manus-storage/david-raya_6ed9fe89.jpg",
  "Franz Beckenbauer": "/manus-storage/franz-beckenbauer_9ffbccf2.jpg",
  "Paolo Maldini": "/manus-storage/paolo-maldini_283fba14.jpg",
  "Alessandro Nesta": "/manus-storage/alessandro-nesta_9bc9e26d.jpg",
  "Fabio Cannavaro": "/manus-storage/fabio-cannavaro_d742a03a.jpg",
  "Sergio Ramos": "/manus-storage/sergio-ramos_785fed56.jpg",
  "Rio Ferdinand": "/manus-storage/rio-ferdinand_f9b3a5bc.jpg",
  "Virgil van Dijk": "/manus-storage/virgil-van-dijk_91315511.jpg",
  "Carles Puyol": "/manus-storage/carles-puyol_9bd22b14.jpg",
  "William Saliba": "/manus-storage/william-saliba_796dfb8c.jpg",
  "Rúben Dias": "/manus-storage/r-ben-dias_b71c3866.jpg",
  "Thiago Silva": "/manus-storage/thiago-silva_5cc01061.jpg",
  "Alessandro Bastoni": "/manus-storage/alessandro-bastoni_d1eb8219.jpg",
  "Ronald Araújo": "/manus-storage/ronald-ara-jo_17b37cfa.jpg",
  "Aymeric Laporte": "/manus-storage/aymeric-laporte_bb1f6ec9.jpg",
  "Pau Torres": "/manus-storage/pau-torres_8aa0fccf.jpg",
  "Ibrahima Konaté": "/manus-storage/ibrahima-konat_ca1da2ff.jpg",
  "Philipp Lahm": "/manus-storage/philipp-lahm_e7776446.jpg",
  "Javier Zanetti": "/manus-storage/javier-zanetti_c68b2d09.jpg",
  "Cafu": "/manus-storage/cafu_3692228b.jpg",
  "Dani Alves": "/manus-storage/dani-alves_626e0e0c.jpg",
  "Trent Alexander-Arnold": "/manus-storage/trent-alexander-arnold_5be5a264.jpg",
  "Achraf Hakimi": "/manus-storage/achraf-hakimi_37e36227.jpg",
  "João Cancelo": "/manus-storage/jo-o-cancelo_9fc36f7a.jpg",
  "Dani Carvajal": "/manus-storage/dani-carvajal_a4d63b5c.jpg",
  "Kyle Walker": "/manus-storage/kyle-walker_be3210df.jpg",
  "Jeremie Frimpong": "/manus-storage/jeremie-frimpong_5bb4aa56.jpg",
  "Reece James": "/manus-storage/reece-james_91e1d0d2.jpg",
  "Pedro Porro": "/manus-storage/pedro-porro_c8676e68.jpg",
  "Roberto Carlos": "/manus-storage/roberto-carlos_a97b8559.jpg",
  "Ashley Cole": "/manus-storage/ashley-cole_0ee6f24e.jpg",
  "Jordi Alba": "/manus-storage/jordi-alba_2600fe23.jpg",
  "Alphonso Davies": "/manus-storage/alphonso-davies_f954535f.jpg",
  "Joško Gvardiol": "/manus-storage/jo-ko-gvardiol_b8bb312b.jpg",
  "Leighton Baines": "/manus-storage/leighton-baines_862cbdf9.jpg",
  "Pervis Estupiñán": "/manus-storage/pervis-estupi-n_98369433.jpg",
  "Alejandro Balde": "/manus-storage/alejandro-balde_f65eb190.jpg",
  "Andrés Iniesta": "/manus-storage/andr-s-iniesta_e49fb163.jpg",
  "Andrea Pirlo": "/manus-storage/andrea-pirlo_b182a45f.jpg",
  "Toni Kroos": "/manus-storage/toni-kroos_8144d0ce.jpg",
  "Rodri": "/manus-storage/rodri_688e0044.jpg",
  "Patrick Vieira": "/manus-storage/patrick-vieira_97dbe272.jpg",
  "Yaya Touré": "/manus-storage/yaya-tour_19d9bffb.jpg",
  "Luka Modrić": "/manus-storage/luka-modri_3f6de023.jpg",
  "Jude Bellingham": "/manus-storage/jude-bellingham_8498238c.jpg",
  "Federico Valverde": "/manus-storage/federico-valverde_58896701.jpg",
  "N'Golo Kanté": "/manus-storage/n-golo-kant_884c0d87.jpg",
  "Paul Scholes": "/manus-storage/paul-scholes_3d592139.jpg",
  "İlkay Gündoğan": "/manus-storage/i-lkay-g-ndo-an_7d2f9f8a.jpg",
  "Frenkie de Jong": "/manus-storage/frenkie-de-jong_bbdf4e0a.jpg",
  "Sandro Tonali": "/manus-storage/sandro-tonali_f52a1a1d.jpg",
  "Declan Rice": "/manus-storage/declan-rice_aae42536.jpg",
  "Diego Maradona": "/manus-storage/diego-maradona_728b9dcb.jpg",
  "Zinedine Zidane": "/manus-storage/zinedine-zidane_bebffd7e.jpg",
  "Ronaldinho": "/manus-storage/ronaldinho_3388172c.jpg",
  "Kaká": "/manus-storage/kak_ec869ef3.jpg",
  "Kevin De Bruyne": "/manus-storage/kevin-de-bruyne_4de76d58.jpg",
  "Francesco Totti": "/manus-storage/francesco-totti_913dd832.jpg",
  "Juan Román Riquelme": "/manus-storage/juan-rom-n-riquelme_9812fb56.jpg",
  "Mesut Özil": "/manus-storage/mesut-zil_a7e3deb1.jpg",
  "Jamal Musiala": "/manus-storage/jamal-musiala_9a26d196.jpg",
  "Phil Foden": "/manus-storage/phil-foden_95abe7ff.jpg",
  "Bruno Fernandes": "/manus-storage/bruno-fernandes_380c0978.jpg",
  "Cole Palmer": "/manus-storage/cole-palmer_8bbc65fe.jpg",
  "Paulo Dybala": "/manus-storage/paulo-dybala_071593de.jpg",
  "Martin Ødegaard": "/manus-storage/martin-degaard_2b8382be.jpg",
  "Lionel Messi": "/manus-storage/lionel-messi_e9e3cb64.jpg",
  "Garrincha": "/manus-storage/garrincha_ecf2d67b.jpg",
  "Arjen Robben": "/manus-storage/arjen-robben_b5c25c55.jpg",
  "David Beckham": "/manus-storage/david-beckham_e1ebd7ec.jpg",
  "Mohamed Salah": "/manus-storage/mohamed-salah_2bfce852.jpg",
  "Bernardo Silva": "/manus-storage/bernardo-silva_0286ab38.jpg",
  "Bukayo Saka": "/manus-storage/bukayo-saka_78e794ca.jpg",
  "Riyad Mahrez": "/manus-storage/riyad-mahrez_9b3e6110.jpg",
  "Lamine Yamal": "/manus-storage/lamine-yamal_b2878bf5.jpg",
  "Michael Olise": "/manus-storage/michael-olise_408c61ad.jpg",
  "Ousmane Dembélé": "/manus-storage/ousmane-demb-l_fb912dc9.jpg",
  "Cristiano Ronaldo": "/manus-storage/cristiano-ronaldo_fc4a76db.jpg",
  "Thierry Henry": "/manus-storage/thierry-henry_d28e2340.jpg",
  "Neymar": "/manus-storage/neymar_c7d8f41f.jpg",
  "Eden Hazard": "/manus-storage/eden-hazard_e2f11865.jpg",
  "Franck Ribéry": "/manus-storage/franck-rib-ry_1c242f30.jpg",
  "Vinícius Júnior": "/manus-storage/vin-cius-j-nior_0adb6355.jpg",
  "Kylian Mbappé": "/manus-storage/kylian-mbapp_d976d9f1.jpg",
  "Sadio Mané": "/manus-storage/sadio-man_cb4f6d4e.jpg",
  "Son Heung-min": "/manus-storage/son-heung-min_56d336a1.jpg",
  "Khvicha Kvaratskhelia": "/manus-storage/khvicha-kvaratskhelia_cfc73c0d.jpg",
  "Jack Grealish": "/manus-storage/jack-grealish_f42038ed.jpg",
  "Marco van Basten": "/manus-storage/marco-van-basten_187eb999.jpg",
  "Erling Haaland": "/manus-storage/erling-haaland_86bef5c0.jpg",
  "Robert Lewandowski": "/manus-storage/robert-lewandowski_4fa0e790.jpg",
  "Luis Suárez": "/manus-storage/luis-su-rez_84d5ec40.jpg",
  "Karim Benzema": "/manus-storage/karim-benzema_02c94c88.jpg",
  "Samuel Eto'o": "/manus-storage/samuel-eto-o_7974cc29.jpg",
  "Harry Kane": "/manus-storage/harry-kane_1df2abc2.jpg",
  "Zlatan Ibrahimović": "/manus-storage/zlatan-ibrahimovi_e28d42bc.jpg",
  "Andriy Shevchenko": "/manus-storage/andriy-shevchenko_8e8481d1.jpg",
  "Sergio Agüero": "/manus-storage/sergio-ag-ero_478af9ea.jpg",
  "Didier Drogba": "/manus-storage/didier-drogba_f46bd17b.jpg",
  "Victor Osimhen": "/manus-storage/victor-osimhen_c358e754.jpg",
  "Viktor Gyökeres": "/manus-storage/viktor-gy-keres_7ffc827f.jpg",
  "Lautaro Martínez": "/manus-storage/lautaro-mart-nez_749c787d.jpg",
  "Alejandro Grimaldo": "/manus-storage/alejandro-grimaldo_1a955af5.jpg",
  "Ederson": "/manus-storage/ederson_aba74cca.jpg",
  "Julián Álvarez": "/manus-storage/juli-n-lvarez_22fefd5c.jpg",
  "Luis Díaz": "/manus-storage/luis-d-az_25c6008b.jpg",
  "Luis Figo": "/manus-storage/luis-figo_e786cede.jpg",
  "Marcelo": "/manus-storage/marcelo_2d0149e0.jpg",
  "Nuno Mendes": "/manus-storage/nuno-mendes_6702d02a.jpg",
  "Ronaldo Nazário": "/manus-storage/ronaldo-naz-rio_6e76a400.jpg",
  "Theo Hernández": "/manus-storage/theo-hern-ndez_63da028a.jpg",
  "Xavi": "/manus-storage/xavi_c7df3a71.jpg"
};
