export type VarDecision = "هدف" | "ضربة جزاء" | "كارت أحمر" | "استمرار اللعب";
export type VarRoundType = "penalty" | "offside" | "goal" | "red-card" | "foul" | "change";

export type VarRound = {
  id: number;
  type: VarRoundType;
  badge: string;
  title: string;
  minute: string;
  description: string;
  varInfo: string;
  originalDecision?: VarDecision;
  options: string[];
  correctAnswer: VarDecision;
  changeAnswer?: "نعم" | "لا";
  explanation: string;
  comment: string;
  isReal?: boolean;
  match?: string;
  teams?: string;
  players?: string[];
  verificationRef: string;
  verificationSource: { title: string; url: string };
};

export const VAR_DECISIONS: VarDecision[] = ["هدف", "ضربة جزاء", "كارت أحمر", "استمرار اللعب"];

const realVarRounds: VarRound[] = [
  { id: 101, type: "goal", badge: "واقعة حقيقية · هدف ولا لأ؟", title: "هدف لويس دياز الملغي", minute: "26:00", match: "توتنهام 2–1 ليفربول · الدوري الإنجليزي · 30 سبتمبر 2023", teams: "ليفربول × توتنهام", players: ["لويس دياز", "كودي جاكبو", "كريستيان روميرو"], description: "لويس دياز سجل هدفاً لليفربول، لكن راية التسلل ظهرت ولم يُحتسب الهدف. لا تنخدع باللقطة الأولى: ما القرار الذي كان يجب أن يخرج؟", varInfo: "التسجيل الصوتي كشف أن غرفة VAR فهمت قرار الحكم الميداني بالعكس ولم تُجرِ المراجعة الصحيحة.", originalDecision: "استمرار اللعب", options: VAR_DECISIONS, correctAnswer: "هدف", explanation: "دياز لم يكن متسللاً. الهدف كان يجب أن يُحتسب، واعتُبر ما حدث خطأً واضحاً في بروتوكول التواصل بين الحكم وVAR.", comment: "دي لقطة الـVAR نفسه قال بعدها: يا نهار أبيض.", isReal: true, verificationRef: "Sky Sports / PGMOL VAR audio report — Tottenham v Liverpool, 30 Sep 2023", verificationSource: { title: "Sky Sports — Luis Díaz VAR audio report", url: "https://www.skysports.com/football/news/11095/12975648/var-audio-released-from-liverpools-disallowed-goal-by-luis-diaz-in-defeat-at-spurs" } },
  { id: 102, type: "goal", badge: "واقعة حقيقية · خط الملعب", title: "كرة اليابان على الخط", minute: "51:00", match: "اليابان 2–1 إسبانيا · كأس العالم 2022", teams: "اليابان × إسبانيا", players: ["كاورو ميتوما", "أو تاناكا", "ريتسو دوان"], description: "كرة كاورو ميتوما أبقاها داخل الملعب قبل صناعة هدف اليابان الثاني، رغم أن زاوية البث جعلتها تبدو خارج الخط بالكامل.", varInfo: "المراجعة التقنية قارنت إسقاط الكرة بالخط، وليس شكلها من زاوية الكاميرا الجانبية.", originalDecision: "هدف", options: VAR_DECISIONS, correctAnswer: "هدف", explanation: "جزء من الكرة ظل فوق الخط؛ لذلك لم تخرج الكرة بالكامل واحتُسب الهدف وفق القانون.", comment: "الصورة قالت برّه، والتكنولوجيا قالت لسه جوّه.", isReal: true, verificationRef: "FIFA World Cup 2022 official match coverage — Japan v Spain, 1 Dec 2022", verificationSource: { title: "BBC Sport — Japan 2–1 Spain", url: "https://www.bbc.co.uk/sport/football/63829718" } },
  { id: 103, type: "goal", badge: "واقعة حقيقية · خطأ VAR", title: "هدف ماكسويل كورنيه الملغي", minute: "90+1", match: "تشيلسي 2–1 وست هام · الدوري الإنجليزي · 3 سبتمبر 2022", teams: "تشيلسي × وست هام", players: ["ماكسويل كورنيه", "جارود بوين", "إدوار ميندي"], description: "ماكسويل كورنيه سجل التعادل لوست هام في اللحظات الأخيرة، لكن الهدف أُلغي بسبب احتكاك جارود بوين مع إدوار ميندي.", varInfo: "PGMOL أقرّ أن تدخل VAR في اللقطة كان خاطئاً وأن قرار إلغاء الهدف لم يكن تصحيحاً واضحاً لخطأ بيّن.", originalDecision: "هدف", options: VAR_DECISIONS, correctAnswer: "هدف", explanation: "الهدف كان يجب أن يبقى محتسباً؛ التدخل لم يبرر إلغاء قرار الحكم الميداني، واعترف PGMOL بالخطأ.", comment: "هدف في آخر ثانية واتشال بقرار خلّى وست هام يفقد أعصابه.", isReal: true, verificationRef: "Sky Sports / PGMOL report — Chelsea v West Ham, 3 Sep 2022", verificationSource: { title: "Sky Sports — West Ham disallowed equaliser", url: "https://www.skysports.com/football/news/11095/12689120/david-moyes-west-ham-manager-brands-late-disallowed-goal-at-chelsea-as-a-ridiculously-bad-call" } },
  { id: 104, type: "goal", badge: "واقعة حقيقية · هدف ملغي", title: "هدف بَرفيس إستوبينيان", minute: "33:00", match: "كريستال بالاس 1–1 برايتون · الدوري الإنجليزي · 11 فبراير 2023", teams: "كريستال بالاس × برايتون", players: ["بَرفيس إستوبينيان", "إيبيريتشي إيزي", "سولي مارش"], description: "برايتون سجل عن طريق بَرفيس إستوبينيان، لكن خطوط التسلل رُسمت بطريقة خاطئة وأُعلن الهدف تسللاً.", varInfo: "PGMOL قال إن خطوط التسلل في غرفة VAR رُسمت بشكل غير صحيح، وإن الهدف كان يجب أن يقف.", originalDecision: "استمرار اللعب", options: VAR_DECISIONS, correctAnswer: "هدف", explanation: "الهدف كان صحيحاً؛ الخطأ لم يكن في تقدير قدم اللاعب فقط، بل في رسم خط التسلل نفسه.", comment: "المشكلة المرة دي كانت في الخط… مش في اللاعب.", isReal: true, verificationRef: "Brighton & Hove Albion / PGMOL statement — Crystal Palace v Brighton, 11 Feb 2023", verificationSource: { title: "Brighton & Hove Albion — PGMOL statement", url: "https://www.brightonandhovealbion.com/media-article/PGMOL-statement-on-disallowed-goal-at-Palace" } },
  { id: 105, type: "goal", badge: "واقعة حقيقية · هدف ملغي", title: "هدف تيرِك ميتشل العكسي", minute: "52:00", match: "نيوكاسل 0–0 كريستال بالاس · الدوري الإنجليزي · 3 سبتمبر 2022", teams: "نيوكاسل × كريستال بالاس", players: ["جو ويلوك", "تيرِك ميتشل", "نيك بوب"], description: "هدف عكسي من تيرِك ميتشل منح نيوكاسل التقدم، لكن الحكم ألغاه بعد مراجعة احتكاك جو ويلوك مع حارس بالاس.", varInfo: "المراجعات اللاحقة اعتبرت أن احتكاك ويلوك لم يكن سبباً كافياً لإلغاء الهدف.", originalDecision: "هدف", options: VAR_DECISIONS, correctAnswer: "هدف", explanation: "كان يجب أن يبقى الهدف قائماً؛ القرار أُلغي بعد تدخل VAR اعتُبر خاطئاً.", comment: "جو ويلوك لمس الحارس؟ السؤال اللي قلب المباراة كلها.", isReal: true, verificationRef: "BBC Sport report — Newcastle v Crystal Palace, 3 Sep 2022", verificationSource: { title: "BBC Sport — Newcastle 0–0 Crystal Palace", url: "https://www.bbc.com/sport/football/62697713" } },
  { id: 106, type: "penalty", badge: "واقعة حقيقية · ضربة جزاء", title: "يد بريسنيل كيمبيمبي", minute: "90+4", match: "باريس سان جيرمان 1–3 مانشستر يونايتد · دوري الأبطال · 6 مارس 2019", teams: "باريس سان جيرمان × مانشستر يونايتد", players: ["بريسنيل كيمبيمبي", "ديوغو دالوت", "ماركوس راشفورد"], description: "تسديدة ديوغو دالوت اصطدمت بذراع بريسنيل كيمبيمبي في الوقت القاتل، والحكم احتاج مراجعة VAR قبل القرار.", varInfo: "الذراع لم تكن قريبة من الجسم، لذلك اعتبرت UEFA أن هناك أساساً لاحتساب ضربة الجزاء.", originalDecision: "استمرار اللعب", options: VAR_DECISIONS, correctAnswer: "ضربة جزاء", explanation: "القرار النهائي كان ضربة جزاء لمانشستر يونايتد، وسجل ماركوس راشفورد منها هدف التأهل.", comment: "آخر دقيقة في باريس… والذراع كانت صاحبة القرار.", isReal: true, verificationRef: "UEFA Champions League official match record — Paris Saint-Germain v Manchester United, 6 Mar 2019", verificationSource: { title: "BBC Sport — UEFA backs PSG penalty decision", url: "https://www.bbc.com/sport/football/47495707" } },
  { id: 107, type: "penalty", badge: "واقعة حقيقية · لمسة يد", title: "يد إيفان بيريشيتش", minute: "38:00", match: "فرنسا 4–2 كرواتيا · نهائي كأس العالم 2018", teams: "فرنسا × كرواتيا", players: ["إيفان بيريشيتش", "أنطوان غريزمان", "بول بوجبا"], description: "ركلة ركنية اصطدمت بيد إيفان بيريشيتش داخل منطقة الجزاء، والحكم لم يحتسب شيئاً قبل الرجوع إلى الشاشة.", varInfo: "المراجعة ركزت على وضع الذراع وهل صنعت مساحة غير طبيعية أم لا.", originalDecision: "استمرار اللعب", options: VAR_DECISIONS, correctAnswer: "ضربة جزاء", explanation: "بعد المراجعة احتُسبت ضربة جزاء لفرنسا، وسجل أنطوان غريزمان هدفاً في النهائي.", comment: "نهائي كأس العالم نفسه دخل غرفة الـVAR بسبب لمسة اليد.", isReal: true, verificationRef: "FIFA World Cup 2018 official match record — France v Croatia final, 15 Jul 2018", verificationSource: { title: "The Express — Perišić handball penalty controversy", url: "https://www.express.co.uk/sport/football/989192/World-Cup-final-VAR-Ivan-Perisic-handball-France-penalty-controversy" } },
  { id: 108, type: "offside", badge: "واقعة حقيقية · تسلل", title: "ثلاثة أهداف أُلغيَت للاوتارو", minute: "22:00", match: "الأرجنتين 1–2 السعودية · كأس العالم 2022", teams: "الأرجنتين × السعودية", players: ["لاوتارو مارتينيز", "ليونيل ميسي", "صالح الشهري"], description: "الأرجنتين سجلت أكثر من مرة، لكن أهدافاً للاوتارو مارتينيز أُلغيت بعد مراجعة التسلل شبه الآلية.", varInfo: "التقنية حددت لحظة التمريرة وأجزاء الجسم القابلة للتسجيل بدقة، لذلك لا تكفي الصورة العادية للحكم.", originalDecision: "هدف", options: VAR_DECISIONS, correctAnswer: "استمرار اللعب", explanation: "الأهداف أُلغيت بسبب التسلل، حتى لو بدت اللقطة متقاربة جداً للعين المجردة.", comment: "السنتمترات هنا كانت أقوى من احتفالات الأرجنتين.", isReal: true, verificationRef: "FIFA World Cup 2022 official match record — Argentina v Saudi Arabia, 22 Nov 2022", verificationSource: { title: "BBC Sport — Saudi Arabia 2–1 Argentina", url: "https://www.bbc.com/sport/football/63631779" } },
  { id: 109, type: "foul", badge: "واقعة حقيقية · شد القميص", title: "روميرو يسحب شعر كوكوريلا", minute: "90+6", match: "تشيلسي 2–2 توتنهام · الدوري الإنجليزي · 14 أغسطس 2022", teams: "تشيلسي × توتنهام", players: ["كريستيان روميرو", "مارك كوكوريلا", "هاري كين"], description: "قبل ركنية هدف التعادل، ظهر كريستيان روميرو وهو يشد شعر مارك كوكوريلا داخل منطقة الجزاء.", varInfo: "لم يتدخل VAR في الواقعة، ثم اعترف الحكم السابق مايك دين لاحقاً بأن التدخل كان يجب أن يخضع للمراجعة.", originalDecision: "استمرار اللعب", options: VAR_DECISIONS, correctAnswer: "كارت أحمر", explanation: "اللعبة الأصلية استمرت بلا عقوبة، لكن الواقعة عُدّت خطأ تحكيمياً واضحاً من حيث السلوك والعنف دون الكرة.", comment: "ركنية واحدة فتحت نقاشاً عن الـVAR والتحكيم كله.", isReal: true, verificationRef: "Sky Sports report — Chelsea v Tottenham, 14 Aug 2022", verificationSource: { title: "Sky Sports — Romero/Cucurella VAR error", url: "https://www.skysports.com/football/news/11661/12676049/mike-dean-admits-he-made-wrong-decision-as-var-over-cristian-romeros-hair-pull-on-marc-cucurella-in-chelsea-vs-tottenham" } },
  { id: 110, type: "goal", badge: "واقعة حقيقية · قانون غريب", title: "ركلة إيزي الحرة الملغاة", minute: "53:00", match: "تشيلسي 0–0 كريستال بالاس · الدوري الإنجليزي · 17 أغسطس 2025", teams: "تشيلسي × كريستال بالاس", players: ["إيبيريتشي إيزي", "مارك غيهي", "روبرت سانشيز"], description: "إيبيريتشي إيزي سجل من ركلة حرة مباشرة، لكن VAR راجع وجود لاعب من كريستال بالاس في موقف تسلل مؤثر أمام حارس تشيلسي.", varInfo: "المراجعة لم تسأل فقط هل الكرة دخلت؛ بل هل لاعب متسلل حجب رؤية الحارس أو أثّر على قدرته على التصدي.", originalDecision: "هدف", options: VAR_DECISIONS, correctAnswer: "استمرار اللعب", explanation: "الهدف أُلغي بعد المراجعة بسبب تأثير لاعب متسلل على رؤية الحارس، وفق تفسير القانون في الواقعة.", comment: "ركلة حرة دخلت، لكن لاعب واقف في المكان الغلط غيّر كل حاجة.", isReal: true, verificationRef: "Sky Sports report — Eberechi Eze disallowed goal, Chelsea v Crystal Palace, 17 Aug 2025", verificationSource: { title: "Sky Sports — Eberechi Eze disallowed goal", url: "https://www.skysports.com/football/news/11706/13413718/eberechi-eze-disallowed-goal-why-crystal-palace-forwards-free-kick-was-ruled-out-vs-chelsea-after-var-check" } },
];

export const varRounds = realVarRounds;

export const shuffleVarRounds = (rounds: VarRound[], seed = Math.random()) => {
  const shuffled = [...rounds];
  let state = Math.floor((seed % 1) * 2147483647) || 1;
  const random = () => { state = (state * 48271) % 2147483647; return state / 2147483647; };
  for (let index = shuffled.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [shuffled[index], shuffled[swapIndex]] = [shuffled[swapIndex], shuffled[index]];
  }
  return shuffled;
};

export const getRoundTypeLabel = (type: VarRoundType) => ({ penalty: "PENALTY REVIEW", offside: "OFFSIDE REVIEW", goal: "GOAL REVIEW", "red-card": "RED CARD REVIEW", foul: "FOUL REVIEW", change: "DECISION REVIEW" }[type]);
